name: flutter_01_alpha
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_platform_widgets: ^1.12.1
  flutter_staggered_animations: 1.0.0
  animations: 2.0.2
  http: 0.13.4
  google_fonts: ^2.1.1
  json_annotation: ^4.4.0
  email_validator: ^2.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  get: ^4.6.1

dev_dependencies:
  effective_dart: 1.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.7
  json_serializable: ^6.1.3

flutter:

  uses-material-design: true

  assets:
    - logo.png
    - elevator-btn.png
    - test-img.png